version: '3.8'

services:
  app:
    build:
      context: ./api_0.1
    volumes:
      - ./api_0.1:/var/www/html
    ports:
      - "9000:9000"
    environment:
      - APP_NAME=${APP_NAME}
      - APP_ENV=${APP_ENV}
      - APP_KEY=${APP_KEY}
      - APP_DEBUG=${APP_DEBUG}
      - APP_URL=${APP_URL}
      - FRONTEND_URL=${FRONTEND_URL}
      - LOG_CHANNEL=${LOG_CHANNEL}
      - LOG_DEPRECATIONS_CHANNEL=${LOG_DEPRECATIONS_CHANNEL}
      - LOG_LEVEL=${LOG_LEVEL}
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - BROADCAST_DRIVER=${BROADCAST_DRIVER}
      - CACHE_DRIVER=${CACHE_DRIVER}
      - FILESYSTEM_DISK=${FILESYSTEM_DISK}
      - QUEUE_CONNECTION=${QUEUE_CONNECTION}
      - SESSION_DRIVER=${SESSION_DRIVER}
      - SESSION_LIFETIME=${SESSION_LIFETIME}
      - MEMCACHED_HOST=${MEMCACHED_HOST}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=${REDIS_PORT}
      - MAIL_MAILER=${MAIL_MAILER}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_ENCRYPTION=${MAIL_ENCRYPTION}
      - MAIL_FROM_ADDRESS=${MAIL_FROM_ADDRESS}
      - MAIL_FROM_NAME=${MAIL_FROM_NAME}
      - MAIL_SMTP_OPTIONS=${MAIL_SMTP_OPTIONS}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - AWS_BUCKET=${AWS_BUCKET}
      - AWS_USE_PATH_STYLE_ENDPOINT=${AWS_USE_PATH_STYLE_ENDPOINT}
      - PUSHER_APP_ID=${PUSHER_APP_ID}
      - PUSHER_APP_KEY=${PUSHER_APP_KEY}
      - PUSHER_APP_SECRET=${PUSHER_APP_SECRET}
      - PUSHER_APP_ID_2=${PUSHER_APP_ID_2}
      - PUSHER_APP_KEY_2=${PUSHER_APP_KEY_2}
      - PUSHER_APP_SECRET_2=${PUSHER_APP_SECRET_2}
      - PUSHER_APP_CLUSTER_2=${PUSHER_APP_CLUSTER_2}
      - PUSHER_APP_ID_3=${PUSHER_APP_ID_3}
      - PUSHER_APP_KEY_3=${PUSHER_APP_KEY_3}
      - PUSHER_APP_SECRET_3=${PUSHER_APP_SECRET_3}
      - PUSHER_APP_CLUSTER_3=${PUSHER_APP_CLUSTER_3}
      - PUSHER_APP_ID_4=${PUSHER_APP_ID_4}
      - PUSHER_APP_KEY_4=${PUSHER_APP_KEY_4}
      - PUSHER_APP_SECRET_4=${PUSHER_APP_SECRET_4}
      - PUSHER_APP_CLUSTER_4=${PUSHER_APP_CLUSTER_4}
      - PUSHER_APP_ID_5=${PUSHER_APP_ID_5}
      - PUSHER_APP_KEY_5=${PUSHER_APP_KEY_5}
      - PUSHER_APP_SECRET_5=${PUSHER_APP_SECRET_5}
      - PUSHER_APP_CLUSTER_5=${PUSHER_APP_CLUSTER_5}
      - PUSHER_HOST=${PUSHER_HOST}
      - PUSHER_PORT=${PUSHER_PORT}
      - PUSHER_SCHEME=${PUSHER_SCHEME}
      - PUSHER_APP_CLUSTER=${PUSHER_APP_CLUSTER}
      - VITE_PUSHER_APP_KEY=${VITE_PUSHER_APP_KEY}
      - VITE_PUSHER_HOST=${VITE_PUSHER_HOST}
      - VITE_PUSHER_PORT=${VITE_PUSHER_PORT}
      - VITE_PUSHER_SCHEME=${VITE_PUSHER_SCHEME}
      - VITE_PUSHER_APP_CLUSTER=${VITE_PUSHER_APP_CLUSTER}
      - FACEBOOK_APP_ID=${FACEBOOK_APP_ID}
      - FACEBOOK_APP_SECRET=${FACEBOOK_APP_SECRET}
      - FACEBOOK_PAGE_ACCESS_TOKEN=${FACEBOOK_PAGE_ACCESS_TOKEN}
      - FACEBOOK_PAGE_APP_SECRET=${FACEBOOK_PAGE_APP_SECRET}
      - FACEBOOK_WEBHOOK_VERIFY_TOKEN=${FACEBOOK_WEBHOOK_VERIFY_TOKEN}
      - FACEBOOK_WEBHOOK_URL=${FACEBOOK_WEBHOOK_URL}
      - TWILIO_SID=${TWILIO_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_PHONE_NUMBER=${TWILIO_PHONE_NUMBER}
    depends_on:
      - db
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
volumes:
  db_data:
